theme: jekyll-theme-slate

title: My Futuristic Website
description: A personal website showcasing my research and interests.

# Navigation Links
header_pages:
  - index.md
  - profile.md
  - acadhrix.md
  - explore.md
  - contact.md
